# Generated by Django 5.2.8 on 2025-11-14 11:37

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(default='latest', max_length=10)),
                ('language', models.CharField(default='en', max_length=2)),
                ('type', models.CharField(max_length=10)),
                ('subject', models.TextField(blank=True, null=True)),
                ('body', models.JSONField(default=dict)),
                ('variables', models.JSONField(default=list)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'unique_together': {('name', 'language', 'version')},
            },
        ),
    ]
