# Generated by Django 5.2.8 on 2025-11-14 07:43

from django.db import migrations



def truncate_fields(apps, schema_editor):
    Template = apps.get_model('app', 'Template')
    for t in Template.objects.all():
        if t.version:
            t.version = t.version[:10]
        if t.type:
            t.type = t.type[:10]
        if t.language:
            t.language = t.language[:2]
        if t.name:
            t.name = t.name[:255]
        t.save()

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_template_body_html_remove_template_body_text_and_more'),
    ]


    operations = [
        migrations.RunPython(truncate_fields),
    ]
