# Generated by Django 5.2.8 on 2025-11-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20251114_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='language',
            field=models.CharField(default='en', max_length=2000000),
        ),
        migrations.AlterField(
            model_name='template',
            name='name',
            field=models.CharField(max_length=2550000),
        ),
        migrations.AlterField(
            model_name='template',
            name='type',
            field=models.CharField(max_length=10000000),
        ),
        migrations.AlterField(
            model_name='template',
            name='version',
            field=models.CharField(default='latest', max_length=10000000),
        ),
    ]
