# Generated by Django 5.2.8 on 2025-11-14 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_template_language_alter_template_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='language',
            field=models.CharField(default='en', max_length=2),
        ),
        migrations.AlterField(
            model_name='template',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='template',
            name='type',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='template',
            name='version',
            field=models.CharField(default='latest', max_length=10),
        ),
    ]
