# Generated by Django 5.2.8 on 2025-11-14 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_template_language_alter_template_name_and_more'),
        ('app', '0007_truncate_fields'),
    ]

    operations = [
    ]
